service: keionne-vrt-onst-api
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002

  esbuild:
    packager: 'yarn'
    bundle: true
    minify: true
    sourcemap: true

package:
  individually: true
  patterns:
    - 'handler.js'
    - '!node_modules/**'
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-west-1'}
  httpApi: # update to be more restrictive for real apps: https://www.serverless.com/framework/docs/providers/aws/events/http-api/#cors-setup
    cors: true
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: '*'
  environment:
    SLS_STAGE: ${env:SLS_STAGE}

functions:
  graphql:
    handler: src/handlers/graphql.server
    events:
      - http:
          path: api
          method: post
          cors: true
      - http:
          path: api
          method: get
          cors: true
